"""Build an ablation-ready frozen snapshot for SIDI.

Why a second snapshot?
----------------------
SIDI_VALIDATION_SNAPSHOT_V1 intentionally stores only signals that already
passed the existing technical setup (RSI<40, DD, MACD histogram improving and
volume declining). A valid ablation of RSI/MACD/volume must also include the
signals that those rules would have rejected. Filtering the old signal set
would therefore be a false ablation.

This builder:
- reuses the byte-frozen prices/indicators/date-added data from Validation V1;
- builds the UNION of candidates generated by removing one technical rule at a
  time from the frozen SIDI setup;
- preserves frozen V1 PIT/context values whenever a candidate already existed
  in V1;
- computes PIT/context only for genuinely new technical-ablation candidates;
- freezes the resulting union for the final ablation stress test.

No production code/rule is changed.
"""
from __future__ import annotations

import gzip
import hashlib
import json
import pickle
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

import historical_membership as membership
import calibrate_pit_proxy_ttm as cal_ttm
import pit_proxy_ttm_fast as ttm_fast
import backtest_context_filters_pit_oos as pit
import analyze_signal_context_features as feat
import backtest_context_filters as ctxmod

SOURCE_PATH = Path("sidi_validation_snapshot_v1.pkl.gz")
OUT_PATH = Path("sidi_ablation_snapshot_v1.pkl.gz")
MANIFEST_PATH = Path("sidi_ablation_snapshot_v1_manifest.json")
AUDIT_PATH = Path("sidi_ablation_snapshot_v1_signals.csv")
VERSION = "SIDI_ABLATION_SNAPSHOT_V1"
START = "2023-01-01"
END = "2026-09-10"
MIN_COVERAGE = 6
RSI_MAX = 40.0
DD_MIN = 12.0
MAX_HOLD_PADDING = 15


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def finite(x):
    try:
        return bool(np.isfinite(float(x)))
    except Exception:
        return False


def build_union(snapshot):
    """Union of baseline + each one-rule-removed technical candidate set."""
    raw = {}
    counts = {
        "BASELINE_TECH": 0,
        "NO_DD12": 0,
        "NO_RSI40": 0,
        "NO_MACD_IMPROVING": 0,
        "NO_VOLUME_DECLINING": 0,
        "UNION": 0,
    }

    for ticker, ind in snapshot["indicators"].items():
        n = len(ind["dates"])
        ts = {}
        for i in range(62, max(62, n - MAX_HOLD_PADDING - 1)):
            dte = ind["dates"][i]
            if dte < START or dte >= END:
                continue

            r = ind["rsi"][i]
            dd = ind["dd60"][i]
            h = ind["hist"][i]
            hp = ind["hist"][i - 1]
            vd = ind["vdec"][i]
            atr = ind["atr"][i]
            close = ind["close"][i]

            r_finite = finite(r)
            dd_finite = finite(dd)
            macd_finite = finite(h) and finite(hp)
            atr_finite = finite(atr) and float(atr) > 0
            close_finite = finite(close) and float(close) > 0
            if not (r_finite and dd_finite and macd_finite and atr_finite and close_finite):
                continue

            flags = {
                "rsi_ok": float(r) < RSI_MAX,
                "dd_ok": float(dd) <= -DD_MIN,
                "macd_ok": float(h) > float(hp),
                "volume_ok": bool(vd),
            }
            base = flags["rsi_ok"] and flags["dd_ok"] and flags["macd_ok"] and flags["volume_ok"]
            no_dd = flags["rsi_ok"] and flags["macd_ok"] and flags["volume_ok"]
            no_rsi = flags["dd_ok"] and flags["macd_ok"] and flags["volume_ok"]
            no_macd = flags["rsi_ok"] and flags["dd_ok"] and flags["volume_ok"]
            no_vol = flags["rsi_ok"] and flags["dd_ok"] and flags["macd_ok"]

            if base: counts["BASELINE_TECH"] += 1
            if no_dd: counts["NO_DD12"] += 1
            if no_rsi: counts["NO_RSI40"] += 1
            if no_macd: counts["NO_MACD_IMPROVING"] += 1
            if no_vol: counts["NO_VOLUME_DECLINING"] += 1
            if not (base or no_dd or no_rsi or no_macd or no_vol):
                continue

            counts["UNION"] += 1
            ts[dte] = {
                "row_idx": i,
                "entry": float(close),
                "rsi": float(r),
                "dd": float(dd),
                "atr_val": float(atr),
                "rsi_ok": flags["rsi_ok"],
                "dd_ok": flags["dd_ok"],
                "macd_ok": flags["macd_ok"],
                "volume_ok": flags["volume_ok"],
            }
        if ts:
            raw[ticker] = ts

    filtered, member_stats = membership.filter_signal_map(raw, snapshot["date_added"])
    return filtered, counts, member_stats


def main():
    print("=" * 124)
    print(f"BUILD {VERSION}")
    print("=" * 124)
    if not SOURCE_PATH.exists():
        raise FileNotFoundError(SOURCE_PATH)
    with gzip.open(SOURCE_PATH, "rb") as f:
        src = pickle.load(f)
    if src.get("version") != "SIDI_VALIDATION_SNAPSHOT_V1":
        raise RuntimeError(f"Unexpected source snapshot: {src.get('version')}")

    union_map, raw_counts, member_stats = build_union(src)
    union_dates = sorted({d for sigs in union_map.values() for d in sigs})
    union_count = sum(len(v) for v in union_map.values())
    print(f"Union after membership: {union_count} signals on {len(union_dates)} dates")
    print("Raw technical set counts:", json.dumps(raw_counts, indent=2))
    print("Membership:", json.dumps(member_stats, indent=2, default=str))

    # Recompute PIT only because genuinely new technical-ablation candidates did
    # not exist in Validation V1. Existing V1 candidates keep their frozen PIT.
    prices = src["prices"]
    tickers = list(prices)
    sectors = src["sectors"]
    added = src["date_added"]
    pmap = pit.price_maps(prices)

    print("\nFetching statements for NEW ablation candidates (existing V1 records remain frozen)...")
    statements, statement_failures = cal_ttm.fetch_full_statements(tickers)
    state_cache = ttm_fast.build_state_cache(statements, START, END)
    fresh_scores, fresh_coverage = pit.dynamic_scores(union_dates, tickers, sectors, state_cache, pmap, added)

    eligible = {}
    source_counts = {"frozen_v1": 0, "fresh_ablation": 0, "missing_score": 0, "low_coverage": 0}
    for ticker, sigs in union_map.items():
        old_sigs = src["signals"].get(ticker, {})
        for dte, sig in sigs.items():
            old = old_sigs.get(dte)
            if old is not None:
                score = float(old["pit_fund_score"])
                cov = int(old["pit_coverage"])
                source = "frozen_v1"
            else:
                rec = fresh_scores.get(dte, {}).get(ticker)
                if rec is None:
                    source_counts["missing_score"] += 1
                    continue
                score = float(rec["fund_score"])
                cov = int(rec.get("coverage", 0))
                source = "fresh_ablation"
            if cov < MIN_COVERAGE:
                source_counts["low_coverage"] += 1
                continue
            item = dict(sig)
            item["pit_fund_score"] = score
            item["pit_coverage"] = cov
            item["data_source"] = source
            eligible.setdefault(ticker, {})[dte] = item
            source_counts[source] += 1

    eligible_count = sum(len(v) for v in eligible.values())
    print(f"Coverage-eligible union: {eligible_count}")
    print("PIT source counts:", json.dumps(source_counts, indent=2))

    # Context: compute fresh context for the union, but preserve Validation V1
    # context byte-for-byte wherever it already exists.
    print("\nComputing context for union candidates...")
    feat.DOWNLOAD_START = src["price_start"]
    refs = {s: feat.download_reference(s) for s in sorted(set(feat.SECTOR_ETF.values()) | {"SPY", "^VIX"})}
    prices_idx = {t: feat.to_indexed(d) for t, d in prices.items()}
    market_breadth, sector_breadth = feat.breadth_maps(prices_idx, sectors, added)
    fresh_context = ctxmod.build_context(eligible, prices_idx, sectors, refs, market_breadth, sector_breadth)

    final_context = {}
    frozen_ctx = 0
    fresh_ctx = 0
    for ticker, sigs in eligible.items():
        for dte in sigs:
            key = (ticker, dte)
            if key in src["context"]:
                final_context[key] = src["context"][key]
                frozen_ctx += 1
            elif key in fresh_context:
                final_context[key] = fresh_context[key]
                fresh_ctx += 1

    snapshot = {
        "version": VERSION,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_snapshot_version": src["version"],
        "source_snapshot_created_at_utc": src.get("created_at_utc"),
        "signal_start": START,
        "end": END,
        "price_start": src["price_start"],
        "min_coverage": MIN_COVERAGE,
        "prices": prices,
        "indicators": src["indicators"],
        "current_fund_scores": src["current_fund_scores"],
        "signals": eligible,
        "context": final_context,
        "sectors": sectors,
        "date_added": added,
        "fresh_coverage": fresh_coverage,
        "meta": {
            "raw_technical_counts": raw_counts,
            "membership": member_stats,
            "union_after_membership": union_count,
            "eligible_union": eligible_count,
            "pit_sources": source_counts,
            "context_frozen_v1": frozen_ctx,
            "context_fresh_ablation": fresh_ctx,
            "statement_failures": statement_failures,
        },
    }

    with gzip.open(OUT_PATH, "wb", compresslevel=6) as f:
        pickle.dump(snapshot, f, protocol=pickle.HIGHEST_PROTOCOL)

    audit = []
    for ticker, sigs in eligible.items():
        for dte, sig in sigs.items():
            c = final_context.get((ticker, dte), {})
            audit.append({
                "ticker": ticker,
                "signal_date": dte,
                "rsi": sig["rsi"],
                "dd": sig["dd"],
                "rsi_ok": sig["rsi_ok"],
                "dd_ok": sig["dd_ok"],
                "macd_ok": sig["macd_ok"],
                "volume_ok": sig["volume_ok"],
                "pit_fund_score": sig["pit_fund_score"],
                "pit_coverage": sig["pit_coverage"],
                "data_source": sig["data_source"],
                "spy20": c.get("spy20"),
                "abnormal20": c.get("abnormal20"),
            })
    adf = pd.DataFrame(audit).sort_values(["signal_date", "ticker"])
    adf.to_csv(AUDIT_PATH, index=False)

    digest = sha256_file(OUT_PATH)
    manifest = {
        "version": VERSION,
        "created_at_utc": snapshot["created_at_utc"],
        "source_snapshot": src["version"],
        "period": [START, END],
        "snapshot_file": str(OUT_PATH),
        "snapshot_sha256": digest,
        "snapshot_size_bytes": OUT_PATH.stat().st_size,
        "audit_rows": len(adf),
        "meta": snapshot["meta"],
        "method_note": "Frozen Validation V1 values preserved for existing candidates; only newly exposed technical-ablation candidates use refreshed PIT/context.",
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    print(f"\nFrozen ablation snapshot: {OUT_PATH} ({OUT_PATH.stat().st_size/1024/1024:.1f} MiB)")
    print(f"SHA256: {digest}")
    print(f"Audit rows: {len(adf)} | context frozen/fresh={frozen_ctx}/{fresh_ctx}")


if __name__ == "__main__":
    main()
