"""Calibrate the quarterly/TTM PIT proxy against real archived SIDI snapshots.

The archived snapshots were generated by production using yFinance ``info``.
This test checks whether a quarterly/TTM reconstruction reproduces those live
scores materially better than the previous annual-only proxy.
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import yfinance as yf

import calibrate_pit_proxy as cal
import historical_membership as membership
import pit_proxy_ttm as ttm
from modules.ingesta.scoring import _sector_medians, _fund_score

SNAP_DIR = Path("data/history/fundamentals")
REAL_THRESHOLD = 6.5
METRICS = cal.METRICS


def fetch_full_statements(tickers: list[str]):
    cache, failed = {}, []
    n = len(tickers)
    for i, ticker in enumerate(tickers, 1):
        try:
            obj = yf.Ticker(ticker.replace("-", "."))
            qinc = obj.quarterly_income_stmt
            qbal = obj.quarterly_balance_sheet
            qcf = obj.quarterly_cashflow
            inc = obj.income_stmt
            bal = obj.balance_sheet
            cf = obj.cashflow
            if (qinc is None or qinc.empty) and (inc is None or inc.empty):
                raise ValueError("empty income statements")
            cache[ticker] = {
                "qinc": qinc, "qbal": qbal, "qcf": qcf,
                "inc": inc, "bal": bal, "cf": cf,
            }
        except Exception as exc:
            failed.append(ticker)
            if len(failed) <= 20:
                print(f"WARN {ticker}: {type(exc).__name__}: {exc}")
        if i % 25 == 0 or i == n:
            print(f"Statements {i}/{n}: OK={len(cache)} fail={len(failed)}")
        time.sleep(0.05)
    return cache, failed


def proxy_for_snapshot(real: pd.DataFrame, asof: str, tickers: list[str], sectors: dict,
                       cache: dict, added: dict[str, str | None]) -> pd.DataFrame:
    prices = dict(zip(real.ticker.astype(str), pd.to_numeric(real.get("price"), errors="coerce")))
    active = [t for t in tickers if (added.get(t) is None or asof >= added[t]) and t in cache]
    rows = []
    for ticker in active:
        m = ttm.metrics_asof(cache[ticker], asof, prices.get(ticker, np.nan))
        m.update({"ticker": ticker, "sector": sectors.get(ticker, "Unknown"), "asof_date": asof})
        rows.append(m)
    df = pd.DataFrame(rows)
    sm = _sector_medians(df)
    scores = df.apply(lambda r: _fund_score(r, sm), axis=1)
    return pd.concat([df, scores], axis=1)


def main():
    dates = cal.snapshot_dates()
    tickers, sectors = cal.load_master()
    added = membership.load_date_added()
    print(f"Archived snapshots: {len(dates)} ({dates[0]} -> {dates[-1]})")

    cache, failed = fetch_full_statements(tickers)

    pairs_all, per_date = [], []
    coverage_rows = []
    for asof in dates:
        real = pd.read_csv(SNAP_DIR / f"fundamentals_{asof.replace('-', '')}.csv")
        real["ticker"] = real["ticker"].astype(str).str.upper().str.replace(".", "-", regex=False)
        proxy = proxy_for_snapshot(real, asof, tickers, sectors, cache, added)

        keep_real = ["ticker", "fund_score"] + [c for c in METRICS if c in real.columns]
        keep_proxy = ["ticker", "fund_score", "metric_coverage"] + [c for c in METRICS if c in proxy.columns]
        rr = real[keep_real].rename(columns={"fund_score": "real_score", **{c: f"real_{c}" for c in METRICS}})
        pp = proxy[keep_proxy].rename(columns={"fund_score": "proxy_score", **{c: f"proxy_{c}" for c in METRICS}})
        comp = rr.merge(pp, on="ticker", how="inner").dropna(subset=["real_score", "proxy_score"])
        comp["date"] = asof
        pairs_all.append(comp)

        cm = cal.class_metrics(comp.real_score, comp.proxy_score, REAL_THRESHOLD)
        cm.update({
            "date": asof, "n": int(len(comp)),
            "pearson": cal.safe_corr(comp.real_score, comp.proxy_score),
            "spearman": cal.safe_corr(comp.real_score, comp.proxy_score, rank=True),
            "mae": float((comp.proxy_score-comp.real_score).abs().mean()),
            "bias": float((comp.proxy_score-comp.real_score).mean()),
        })
        per_date.append(cm)
        coverage_rows.append({
            "date": asof,
            "n": len(comp),
            "mean_coverage": float(pd.to_numeric(comp.metric_coverage, errors="coerce").mean()),
            "coverage_ge6_pct": float((pd.to_numeric(comp.metric_coverage, errors="coerce") >= 6).mean()*100),
        })
        print(f"{asof}: n={len(comp)} P={cm['pearson']:.3f} S={cm['spearman']:.3f} "
              f"agree65={cm['agreement']:.1%} F1={cm['f1']:.3f} J={cm['jaccard']:.3f}")

    pairs = pd.concat(pairs_all, ignore_index=True)
    diff = pairs.proxy_score - pairs.real_score
    baseline = cal.class_metrics(pairs.real_score, pairs.proxy_score, REAL_THRESHOLD)
    optimum = cal.best_threshold(pairs)
    loso_df, loso = cal.loso_threshold_validation(pairs)

    metric_rows = []
    for m in METRICS:
        rc, pc = f"real_{m}", f"proxy_{m}"
        if rc not in pairs or pc not in pairs:
            continue
        x, y = pd.to_numeric(pairs[rc], errors="coerce"), pd.to_numeric(pairs[pc], errors="coerce")
        ok = x.notna() & y.notna() & np.isfinite(x) & np.isfinite(y)
        metric_rows.append({
            "metric": m, "n": int(ok.sum()),
            "pearson": cal.safe_corr(x[ok], y[ok]),
            "spearman": cal.safe_corr(x[ok], y[ok], rank=True),
            "mae": float((y[ok]-x[ok]).abs().mean()) if ok.sum() else None,
            "median_abs_error": float((y[ok]-x[ok]).abs().median()) if ok.sum() else None,
        })
    metric_df = pd.DataFrame(metric_rows)

    ticker_err = (pairs.assign(abs_error=diff.abs())
                  .groupby("ticker")
                  .agg(n=("real_score","size"), real_mean=("real_score","mean"),
                       proxy_mean=("proxy_score","mean"), mae=("abs_error","mean"))
                  .sort_values("mae", ascending=False).reset_index())

    summary = {
        "generated_at": datetime.utcnow().isoformat()+"Z",
        "method": "quarterly_yoy_growth_plus_ttm_financials",
        "quarter_lag_days": ttm.QUARTER_LAG_DAYS,
        "annual_fallback_lag_days": ttm.ANNUAL_LAG_DAYS,
        "snapshots": len(dates), "pairs": int(len(pairs)),
        "date_range": [dates[0], dates[-1]], "statement_failures": failed,
        "score": {
            "pearson": cal.safe_corr(pairs.real_score, pairs.proxy_score),
            "spearman": cal.safe_corr(pairs.real_score, pairs.proxy_score, rank=True),
            "mae": float(diff.abs().mean()),
            "rmse": float(math.sqrt(np.mean(np.square(diff)))),
            "bias_proxy_minus_real": float(diff.mean()),
        },
        "threshold_6_5": baseline,
        "best_in_sample_proxy_threshold": optimum,
        "leave_one_snapshot_out": loso,
        "annual_proxy_reference_from_previous_calibration": {
            "pearson": 0.31336557775869894,
            "spearman": 0.29522057355964737,
            "mae": 1.2671210161119602,
            "agreement_6_5": 0.7096318946254263,
            "precision_6_5": 0.3527413876758855,
            "recall_6_5": 0.3904403866809882,
            "f1_6_5": 0.37063471832781036,
            "jaccard_6_5": 0.2274718397997497,
        },
        "caveats": [
            "Snapshots are clustered in Aug-Sep 2026.",
            "Quarterly statements use a conservative 45-day lag, not exact filing dates.",
            "Historical yFinance statement values may include later restatements.",
        ],
    }

    Path("sidi_pit_ttm_calibration_summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    pd.DataFrame(per_date).to_csv("sidi_pit_ttm_calibration_by_date.csv", index=False)
    pd.DataFrame(coverage_rows).to_csv("sidi_pit_ttm_calibration_coverage.csv", index=False)
    metric_df.to_csv("sidi_pit_ttm_calibration_by_metric.csv", index=False)
    loso_df.to_csv("sidi_pit_ttm_calibration_loso.csv", index=False)
    ticker_err.head(100).to_csv("sidi_pit_ttm_calibration_ticker_mismatches.csv", index=False)

    print("\n=== TTM CALIBRATION SUMMARY ===")
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
